### ISSUE TITLE
pre 超出文本不换行 希望增加如下的css代码

### ISSUE THREAD

**Issue by eluotao** [shunfei/cronsun#191]
希望增加以下代码到 <pre class="ui inverted segment">{{printResult}}</pre> 到下面的 class 类

```css
pre{
    white-space: pre-wrap;       /* css-3 */
    white-space: -moz-pre-wrap;  /* Mozilla, since 1999 */
    white-space: -pre-wrap;      /* Opera 4-6 */
    white-space: -o-pre-wrap;    /* Opera 7 */
    word-wrap: break-word;       /* Internet Explorer 5.5+ */
    overflow: auto;
    word-break: break-all;
}
```

可以实现日志文本超出  自动换行  目前文本超出是不显示的 得复制出来才能看到
